export enum BlockchainError {
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  UNAUTHORIZED_ISSUER = 'UNAUTHORIZED_ISSUER',
  UNAUTHORIZED_SENDER = 'UNAUTHORIZED_SENDER',
  UNKNOWN_IDENTITY = 'UNKNOWN_IDENTITY',
  REPLAY_DETECTED = 'REPLAY_DETECTED',
  REPLAYED_TRANSACTION = 'REPLAYED_TRANSACTION',
  INVALID_BLOCK = 'INVALID_BLOCK',
  INVALID_BLOCK_STRUCTURE = 'INVALID_BLOCK_STRUCTURE',
  INVALID_MERKLE_ROOT = 'INVALID_MERKLE_ROOT',
  INVALID_MERKLE_PROOF = 'INVALID_MERKLE_PROOF',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  UNKNOWN_CREDENTIAL = 'UNKNOWN_CREDENTIAL',
  UNKNOWN_ISSUER = 'UNKNOWN_ISSUER',
  UNKNOWN_VALIDATOR = 'UNKNOWN_VALIDATOR',
  UNKNOWN_KEY = 'UNKNOWN_KEY',
  STORAGE_ERROR = 'STORAGE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  CONSENSUS_ERROR = 'CONSENSUS_ERROR',
  UNSUPPORTED_VERSION = 'UNSUPPORTED_VERSION',
  DUPLICATE_BLOCK = 'DUPLICATE_BLOCK',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  INVALID_PREVIOUS_HASH = 'INVALID_PREVIOUS_HASH',
  INVALID_BLOCK_HEIGHT = 'INVALID_BLOCK_HEIGHT',
  INVALID_PROPOSER_SIGNATURE = 'INVALID_PROPOSER_SIGNATURE',
  UNAUTHORIZED_VALIDATOR = 'UNAUTHORIZED_VALIDATOR',
  MISSING_SIGNATURE = 'MISSING_SIGNATURE',
  INVALID_TX_ID = 'INVALID_TX_ID',
  INVALID_NONCE = 'INVALID_NONCE',
  INVALID_SENDER = 'INVALID_SENDER',
  UNKNOWN_TX_TYPE = 'UNKNOWN_TX_TYPE',
  UNSUPPORTED_TX_TYPE = 'UNSUPPORTED_TX_TYPE',
  UNSUPPORTED_PROTOCOL_VERSION = 'UNSUPPORTED_PROTOCOL_VERSION',
  UNSUPPORTED_TRANSACTION_VERSION = 'UNSUPPORTED_TRANSACTION_VERSION',
  UNSUPPORTED_BLOCK_VERSION = 'UNSUPPORTED_BLOCK_VERSION',
  CREDENTIAL_ALREADY_EXISTS = 'CREDENTIAL_ALREADY_EXISTS',
  CREDENTIAL_NOT_IN_BLOCK = 'CREDENTIAL_NOT_IN_BLOCK',
  ISSUER_ALREADY_REGISTERED = 'ISSUER_ALREADY_REGISTERED',
  ISSUER_REVOKED = 'ISSUER_REVOKED',
  KEY_ALREADY_REGISTERED = 'KEY_ALREADY_REGISTERED',
  KEY_NOT_ACTIVE = 'KEY_NOT_ACTIVE',
  NEW_KEY_ALREADY_REGISTERED = 'NEW_KEY_ALREADY_REGISTERED',
  NEW_CREDENTIAL_ALREADY_EXISTS = 'NEW_CREDENTIAL_ALREADY_EXISTS',
  CREDENTIAL_ALREADY_REVOKED = 'CREDENTIAL_ALREADY_REVOKED',
  CREDENTIAL_ALREADY_SUSPENDED = 'CREDENTIAL_ALREADY_SUSPENDED',
  BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',
  CORRUPTED_STORAGE = 'CORRUPTED_STORAGE',
  INVALID_GENESIS_PREVIOUS_HASH = 'INVALID_GENESIS_PREVIOUS_HASH',
  INVALID_GENESIS_HEIGHT = 'INVALID_GENESIS_HEIGHT',
  GENESIS_MUST_BE_EMPTY = 'GENESIS_MUST_BE_EMPTY',
  INVALID_VALIDATOR_SIGNATURE = 'INVALID_VALIDATOR_SIGNATURE',
}

export interface BlockchainResult<T = void> {
  success: boolean;
  data?: T;
  error?: BlockchainError;
  message?: string;
}

export function ok<T>(data: T): BlockchainResult<T> {
  return { success: true, data };
}

export function fail<T = void>(error: BlockchainError, message?: string): BlockchainResult<T> {
  return { success: false, error, message };
}
